# SPDX-FileCopyrightText: 2025 Olav and Niklas Seyfarth, Contributors <https://github.com/datenschutz-individuell/twofactor_email/blob/main/CONTRIBUTORS.md>
# SPDX-License-Identifier: MIT

name: Test

on:
  pull_request:
    branches:
      - main
      - master
      - stable*

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: [ "8.1" ]
        nextcloud-version: [ 'stable32' ]
        db: ['sqlite']

    name: Nextcloud ${{ matrix.nextcloud-version }} php${{ matrix.php-version }} unit tests
    steps:
      - name: Set up php${{ matrix.php-version }}
        uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # v2.32.0
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ctype,curl,dom,gd,iconv,intl,json,mbstring,openssl,posix,sqlite,xml,zip
          coverage: xdebug

      - name: Checkout Nextcloud
        run: git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b ${{ matrix.nextcloud-version }} nextcloud

      - name: Install Nextcloud
        run: php -f nextcloud/occ maintenance:install --database-host 127.0.0.1 --database-name nextcloud --database-user nextcloud --database-pass nextcloud --admin-user admin --admin-pass admin --database ${{ matrix.db }}

      - name: Checkout app
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: nextcloud/apps/twofactor_email

      - name: Install dependencies
        working-directory: nextcloud/apps/twofactor_email
        run: composer install

      - name: Run tests
        working-directory: nextcloud/apps/twofactor_email
        run: composer run test:unit

      - name: Report coverage
        uses: codecov/codecov-action@0da7aa657d958d32c117fc47e1f977e7524753c7 # v5.3.0
        if: ${{ always() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./nextcloud/apps/twofactor_email/tests/clover.xml
          flags: unittests
          fail_ci_if_error: true
